# Site settings
title: LEGO
description: 코린이가 개발자가 되기까지
# baseurl: "" # the subpath of your site, e.g. /blog
url: soohyun828.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Soohyun Park
user_description: KHU Software Convergence 21
user_title: Student
email: psh68380@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
